### ISSUE TITLE
Error in redirect when clicking on "tools"

### ISSUE THREAD

**Issue by anaPiris** [Azordev/various-tasks#144] opened 2022-05-08 02:14 UTC
Explanation
In "tools" when clicking on each topic it does not redirect to the correct page, but they all show the same information about Israel Laguan

Current result:
Entering "tools" and clicking on a topic does not show the page that corresponds to the title, but instead shows information about Israel Laguan.

Expected result:
That when entering "tools" and clicking on a topic, it shows the page that corresponds to the title.

Screen size:

the whole screen

Screenshots
![image](https://user-images.githubusercontent.com/74306449/167278883-931f5942-37d4-4664-8385-fe7096f9f3a9.png)

![image](https://user-images.githubusercontent.com/74306449/167278877-d417b515-c174-4ea8-a4fe-75a0ff2a1300.png)

Check list
This issue can be closed when the following tasks are completed:
-That the indicated error be modified.

References
https://github.com/Israel-Laguan/israel-laguan.github.io

**Comment by Israel-Laguan** [comment] 2022-05-10 20:54
I think this is a duplicate of #142, as that are not buttons or links

**Closed as completed by Israel-Laguan** 2022-05-10 20:54 UTC
Labels: duplicate, wontfix
