### ISSUE TITLE
Error In Continuous Redirection Link To The Title  /    Error En El Enlace De Redireccionamiento Contínuo Al Título

### ISSUE THREAD

**Issue by anaPiris** [Azordev/various-tasks#103] opened 2022-05-05 02:31 UTC
###Explanation:
The link "https://github.com/pamigomp/node-mongodb-template", next to the title, does not redirect to any information as its title names it, the page is incomplete without text or photos.

Current result:
Entering "Heavily inspired by "author": "Michal Pietrzak"" you see a link that redirects to another page.

Expected result:
That when entering "Very inspired by "author": "Michal Pietrzak" the link does not redirect to another page. That you see text and photos that refer to "Very inspired by "author": "Michal Pietrzak".

*Screen size:*
Full screen.

### Screenshots:
![image](https://user-images.githubusercontent.com/74306449/166856375-ed26e180-c2b6-4c99-917a-782300c9cc8f.png)

![image](https://user-images.githubusercontent.com/74306449/166856405-571a1cdc-0ad2-4f4f-9cd6-cb6752c55260.png)

![image](https://user-images.githubusercontent.com/74306449/169164185-3c37282a-0edb-4047-a978-4306b4201f06.png)

### Check list:
This issue can be closed when the following tasks are completed:
- Verify the correctness of the title with respect to the link and show the content of the page.

  ### References:
https://github.com/Israel-Laguan/express-graphql-mongoose

Spanish Version:

###Explicación:
El enlace "https://github.com/pamigomp/node-mongodb-template", al lado del título, no redirige a ninguna información como su título lo nombra, la página está incompleta sin texto ni fotos.

Resultado actual:
Al ingresar a "Fuertemente inspirado por "autor": "Michal Pietrzak"" se observa un enlace que no redirige a información como se menciona en el título del mismo, no tiene texto ni fotos.

Resultado Esperado:
Que al ingresar "Muy inspirado por "autor": "Michal Pietrzak"" el enlace redirige a información referente a su título y que la página muestre textos y fotos que motiven el interés por la misma.

*Tamaño de pantalla:*
Pantalla completa.

### Capturas de pantalla:
![imagen](https://user-images.githubusercontent.com/74306449/166856375-ed26e180-c2b6-4c99-917a-782300c9cc8f.png)

![imagen](https://user-images.githubusercontent.com/74306449/166856405-571a1cdc-0ad2-4f4f-9cd6-cb6752c55260.png)

![imagen](https://user-images.githubusercontent.com/74306449/169164185-3c37282a-0edb-4047-a978-4306b4201f06.png)

### Lista de Verificación:
Este problema se puede cerrar cuando se completen las siguientes tareas:
- Verificar la corrección del título con respecto al enlace y mostrar el contenido de la página.

  ### Referencias:
https://github.com/Israel-Laguan/express-graphql-mongoose

**Comment by Israel-Laguan** [comment] 2022-05-05 13:55
Please explain more the issue, I don't get how it can be solved/verified

**Comment by Israel-Laguan** [comment] 2022-05-06 01:14
Maybe change to something on the line of "explain in what way it took inspiration from that other repo"

**Comment by angelik0828** [comment] 2022-05-18 21:56
@arodriguezl9302 to be able to take this task you must be with the checks that the other tasks have
![image](https://user-images.githubusercontent.com/4030477/169162578-c7c9d8fd-65ad-4bab-9712-c3b365cd17c0.png)

**Comment by mdrianislam0or1** [comment] 2022-05-19 23:36
Is that issue ready for work?

**Comment by angelik0828** [comment] 2022-05-31 20:31
@mdrianislam0or1 yes it's ready!!

**Comment by mdrianislam0or1** [comment] 2022-06-01 11:04
@angelik0828 what is the expected solution?Explain Clearly.

**Comment by Israel-Laguan** [comment] 2022-06-06 05:55
> @angelik0828 what is the expected solution?Explain Clearly.

I think the issue is invalid. The QA originally mentioned the repo mentioned doesn't have a proper Readme, but that is not in us to change as we don't have access to that repo. 

@angelik0828 will close this issue.

**Closed as completed** 2022-06-06 05:55 UTC
Labels: EE-1, invalid, QA check, Translated, Grammar review
